const report = {
  totalPaidAmount: 117342,
  totalPrice: 116592,
  listOfSoldProduct: [
    {
      date: "2024-12-09",
      customerName: "1723",
      officeName: "Trafic Light",
      productName: "PVC Ceiling 30cm",
      productDes: "",
      quantity: 70,
      unit: "Pics",
      price: 415,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1723",
      officeName: "Trafic Light",
      productName: "Big Cornice",
      productDes: "",
      quantity: 20,
      unit: "pcs",
      price: 550,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1723",
      officeName: "Trafic Light",
      productName: "Angle Conner",
      productDes: "",
      quantity: 4,
      unit: "pcs",
      price: 450,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1723",
      officeName: "Trafic Light",
      productName: "Simple Cornite",
      productDes: "",
      quantity: 9,
      unit: "pcs",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1723",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 1,
      unit: "cups",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1724",
      officeName: "Trafic Light",
      productName: "Big Cornice",
      productDes: "",
      quantity: 25,
      unit: "pcs",
      price: 600,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1725",
      officeName: "Trafic Light",
      productName: "PVC Ceiling 30cm",
      productDes: "",
      quantity: 6,
      unit: "Pics",
      price: 425,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1726",
      officeName: "Trafic Light",
      productName: "PVC Ceiling 30cm",
      productDes: "",
      quantity: 10,
      unit: "Pics",
      price: 420,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1726",
      officeName: "Trafic Light",
      productName: "Simple Cornite",
      productDes: "",
      quantity: 4,
      unit: "pcs",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1726",
      officeName: "Trafic Light",
      productName: "Wallpaper",
      productDes: "",
      quantity: 2,
      unit: "pcs",
      price: 500,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1726",
      officeName: "Trafic Light",
      productName: "Wallpaper Gule",
      productDes: "",
      quantity: 1,
      unit: "pcs",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1726",
      officeName: "Trafic Light",
      productName: "Wallpaper",
      productDes: "",
      quantity: 1,
      unit: "pcs",
      price: 400,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1727",
      officeName: "Trafic Light",
      productName: "Big Cornice",
      productDes: "",
      quantity: 8,
      unit: "pcs",
      price: 649,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1727",
      officeName: "Trafic Light",
      productName: "Angle Conner",
      productDes: "",
      quantity: 10,
      unit: "pcs",
      price: 500,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1727",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 2,
      unit: "cups",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1727",
      officeName: "Trafic Light",
      productName: "Pvc Nail",
      productDes: "",
      quantity: 4,
      unit: "kg",
      price: 200,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1728",
      officeName: "Trafic Light",
      productName: "PVC Ceiling 30cm",
      productDes: "",
      quantity: 40,
      unit: "Pics",
      price: 430,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1729",
      officeName: "Trafic Light",
      productName: "PVC Ceiling 30cm",
      productDes: "",
      quantity: 15,
      unit: "Pics",
      price: 430,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1730",
      officeName: "Trafic Light",
      productName: "Simple Cornite",
      productDes: "",
      quantity: 0,
      unit: "pcs",
      price: 0,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1730",
      officeName: "Trafic Light",
      productName: "Wallpaper",
      productDes: "",
      quantity: 3,
      unit: "pcs",
      price: 400,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1730",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 3,
      unit: "cups",
      price: 150,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1731",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 1,
      unit: "cups",
      price: 150,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1731",
      officeName: "Trafic Light",
      productName: "Wallpaper",
      productDes: "",
      quantity: 11,
      unit: "pcs",
      price: 400,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1733",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 2,
      unit: "cups",
      price: 175,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1734",
      officeName: "Trafic Light",
      productName: "silicone glue",
      productDes: "",
      quantity: 0,
      unit: "cups",
      price: 0,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1734",
      officeName: "Trafic Light",
      productName: "PS Panel",
      productDes: "",
      quantity: 10,
      unit: "pcs",
      price: 550,
      returnProduct: 0,
      remove: "",
    },
    {
      date: "2024-12-09",
      customerName: "1734",
      officeName: "Trafic Light",
      productName: "Marble",
      productDes: "",
      quantity: 1,
      unit: "pcs",
      price: 1500,
      returnProduct: 0,
      remove: "",
    },
  ],

  totalPaymentList: [
    {
      id: "",
      time: "20:03:37",
      date: "2024-12-09",
      amount: 43850,
      paymentType: "Cash",
      customerName: "1723",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:11:51",
      date: "2024-12-09",
      amount: 15000,
      paymentType: "Cash",
      customerName: "1724",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:15:44",
      date: "2024-12-09",
      amount: 2550,
      paymentType: "Cash",
      customerName: "1725",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:24:18",
      date: "2024-12-09",
      amount: 6200,
      paymentType: "Cash",
      customerName: "1726",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:33:46",
      date: "2024-12-09",
      amount: 400,
      paymentType: "Cash",
      customerName: "1726",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:37:45",
      date: "2024-12-09",
      amount: 11392,
      paymentType: "Cash",
      customerName: "1727",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "18:59:17",
      date: "2024-12-09",
      amount: 17200,
      paymentType: "Cash",
      customerName: "1728",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "19:11:14",
      date: "2024-12-09",
      amount: 6450,
      paymentType: "Cash",
      customerName: "1729",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "19:14:19",
      date: "2024-12-09",
      amount: 2450,
      paymentType: "Cash",
      customerName: "1730",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:17:10",
      date: "2024-12-09",
      amount: 4550,
      paymentType: "Cash",
      customerName: "1731",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:21:55",
      date: "2024-12-09",
      amount: 300,
      paymentType: "Cash",
      customerName: "1733",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
    {
      id: "",
      time: "20:25:46",
      date: "2024-12-09",
      amount: 7000,
      paymentType: "Cash",
      customerName: "1734",
      officeName: "Trafic Light",
      remove: "",
      status: "",
      orderId: "2457286",
    },
  ],
};

const gambiaReportI = [
  {
    date: "12/9/2024",
    "product name": "PVC Ceiling",
    customerName: 1723,
    quantity: 70,
    price: 415,
    total: "29,050",
  },
  {
    date: "12/9/2024",
    "product name": "Design Big Cornix",
    customerName: 1723,
    quantity: 20,
    price: 550,
    total: "11,000",
  },
  {
    date: "12/9/2024",
    "product name": "Angle Cornix",
    customerName: 1723,
    quantity: 4,
    price: 450,
    total: "1,800",
  },
  {
    date: "12/9/2024",
    "product name": "Simple Cornix",
    customerName: 1723,
    quantity: 9,
    price: 200,
    total: 1800,
  },
  {
    date: "12/9/2024",
    "product name": "Silicone",
    customerName: 1723,
    quantity: 1,
    price: 200,
    total: 200,
  },
  {
    date: "12/9/2024",
    "product name": "Big Cornix",
    customerName: 1724,
    quantity: 25,
    price: 600,
    total: "15,000",
  },
  {
    date: "12/9/2024",
    "product name": "PVC Ceiling",
    customerName: 1725,
    quantity: 6,
    price: 425,
    total: "2,550",
  },
  {
    date: "12/9/2024",
    "product name": "PVC Ceiling",
    customerName: 1726,
    quantity: 10,
    price: 420,
    total: "4,200",
  },
  {
    date: "12/9/2024",
    "product name": "Simple Cornix",
    customerName: 1726,
    quantity: 4,
    price: 200,
    total: 800,
  },
  {
    date: "12/9/2024",
    "product name": "Wall paper",
    customerName: 1726,
    quantity: 2,
    price: 500,
    total: "1,000",
  },
  {
    date: "12/9/2024",
    "product name": "Glue",
    customerName: 1726,
    quantity: 1,
    price: 200,
    total: 200,
  },
  {
    date: "12/9/2024",
    "product name": "Simple Cornix",
    customerName: 1726,
    quantity: 4,
    price: 150,
    total: 600,
  },
  {
    date: "12/9/2024",
    "product name": "Wall paper",
    customerName: 1726,
    quantity: 1,
    price: 400,
    total: 400,
  },
  {
    date: "12/9/2024",
    "product name": "Big Cornix",
    customerName: 1727,
    quantity: 8,
    price: 650,
    total: "5,200",
  },
  {
    date: "12/9/2024",
    "product name": "Angle Cornix",
    customerName: 1727,
    quantity: 10,
    price: 500,
    total: "5,000",
  },
  {
    date: "12/9/2024",
    "product name": "Silicone",
    customerName: 1727,
    quantity: 2,
    price: 200,
    total: 400,
  },
  {
    date: "12/9/2024",
    "product name": "PVC Nail",
    customerName: 1727,
    quantity: 4,
    price: 200,
    total: 800,
  },
  {
    date: "12/9/2024",
    "product name": "PVC Ceiling",
    customerName: 1728,
    quantity: 40,
    price: 430,
    total: "17,200",
  },
  {
    date: "12/9/2024",
    "product name": "PVC Ceiling",
    customerName: 1729,
    quantity: 15,
    price: 430,
    total: "6,400",
  },
  {
    date: "12/9/2024",
    "product name": "Simple Cornix",
    customerName: 1729,
    quantity: 4,
    price: 200,
    total: 800,
  },
  {
    date: "12/9/2024",
    "product name": "Wall papers",
    customerName: 1730,
    quantity: 3,
    price: 400,
    total: "1,200",
  },
  {
    date: "12/9/2024",
    "product name": "Glue",
    customerName: 1730,
    quantity: 3,
    price: 150,
    total: 450,
  },
  {
    date: "12/9/2024",
    "product name": "Glue",
    customerName: 1731,
    quantity: 1,
    price: 150,
    total: 150,
  },
  {
    date: "12/9/2024",
    "product name": "Wall papers",
    customerName: 1731,
    quantity: 11,
    price: 400,
    total: "4,400",
  },
  {
    date: "12/9/2024",
    "product name": "Glue",
    customerName: 1733,
    quantity: 1,
    price: 200,
    total: 200,
  },
  {
    date: "12/9/2024",
    "product name": "Glue",
    customerName: 1733,
    quantity: 1,
    price: 150,
    total: 150,
  },
  {
    date: "12/9/2024",
    "product name": "PS panel",
    customerName: 1734,
    quantity: 10,
    price: 550,
    total: "5,500",
  },
  {
    date: "12/9/2024",
    "product name": "UV board/Marble",
    customerName: 1734,
    quantity: 1,
    price: 1500,
    total: "1,500",
  },
];
